version: "3.8"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=vini
      - POSTGRES_PASSWORD=finances
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres:
